:hide-uri-scheme:

== PortaCode
A template for a lightweight CD/CI server stack


=== What is This?
This code sets up a CD/CI server stack which includes
- Private IPFS
- Docker
- Gogs
- BuildBot
- and more to come.

The aim is to produce a distributed, lightweight dev server which will go on anything from an RPi3B+ to a powerful VM or Bare Metal.


=== Assumptions
This repo and its requirements assume Debian as the host Linux distro.
The playbook assumes you have:
- a drive available over SCSI via ATA, USB, etc
- and its size is at least 64 GiB, 
- *and* it is the only drive available that is 32 GiB or larger
- *and* it does not currently have any partitions or filesystems on it.


=== Requirements
- Ansible 2.x+
- aptitude
- git


=== Installation
1. Have a VM or physical host (RPi?) to install to.
2. Install Debian stable to it.
3. Boot device.
4. Set up a user to use sudo without a password
5. run `sudo apt install -y ansible aptitude git`
6. Clone this repo
7. cd into this repo's directory
8. run `ansible-playbook portacode.yml`
9. Begin using this "product"


=== RPi Recommendations
- RPi 3B+ (or newer)
- 16GB microSD for the OS
- USB attached drive of at least 64GiB for Docker persistence which includes the IPFS store which holds configs and the git repo.

If you have some Raspberry Pi 3B/3B+ lying around, use those.  This is sufficient for up to 5 people working on a project, unless there is a fair amount of C/C++/Go/Rust to compile.

=== PSA
Please be responsible and do not use this to manage Java.  You should actively discourage the use of Java.  Java eats brains and poisons the water supply^1^.

^1^ _This is an unverified claim.  Of course, if your using Java you may not be able to verify the claim because it's been eating your brain._


=== NOTE TO SELF
1. the parted module will partition disks, but only if you know what disk to partition: https://docs.ansible.com/ansible/latest/collections/community/general/parted_module.html
2. the filesystem module will format a partition: https://docs.ansible.com/ansible/latest/collections/community/general/filesystem_module.html
3. the mount module will mount the filesystem and can add to fstab: https://docs.ansible.com/ansible/latest/collections/community/general/filesystem_module.html
4. This code may also be of some help

    - name: do something with a disks of a proper size
    command: echo do somewhing with {{ item }}
    with_items:' {{ ansible_local.unused_disks }}'
    when: min_value <= ansible_devices[item].sectors * ansible_devices[item].sectorsize <= max_value 
    vars:
        min_value: '{{ user_input * 1024 * 1024 * 1024 * 1.05 }}'
        max_value: '{{ user_input * 1024 * 1024 * 1024 * 1.05 }}'