:hide-uri-scheme:

== replicant
A template for a lightweight distributed CD/CI server stack.


=== What is This?
This code sets up a CD/CI server stack which includes

- Distributed Storage (TBD)
- K3S w/ Podman
- Pods!
  * OpenLDAP (metamask auth in progress)
  * go-ipfs
  * PostgreSQL
  * Lighttpd
  * Kallithea
  * Kanboard
  * Trac
  * A pipeline (TBD)

The aim is to produce a distributed, lightweight dev server that will go on anything from an RPi3B+ to a powerful VM or Bare Metal.
With this, you could use a few RPi3B+ which you share with friends, and host your code repo cloud with a URL reachable via IPFS for those with whom you have shared the IPFS URI.  Cluster capability increases linearly with the number of nodes, however, each node is realistically limited to about 5 people.

== Why make this?
Your reasons to use this are your own.  As for me: I have a strong disdain and distrust for centralized systems, especially those supported by a profit motive.  The owner of GitHub in particular tends to Embrace, Enhance, and Extinguish.  In this case, they are using your code hosted here (license permitting) to train AI to write code.  This behavior is, in general, a bad idea.

=== A Brief Tangent on the Qualifications for Training Synthetic Intelligence
This is particularly poignant with General Purpose Artificial Intelligence, but the fact remains that anything that learns behaviors (or any stimulus-response pattern) is biased by the teacher with innumerable nuanced influences from the environment.  This means that if you are not a completely enlightened individual...one without pain tied to your past, nor fear of the future, and able to remain present without tuning out in the present, then you are NOT qualified to train an AI (esp. GPAI).  Your biases (fear, hurts, expectations, desires) will color the data samples and your interpretation of results.  Combine this with the imprecision of spoken (and most written) languages, and a formula for discord and potentially cataclysmic disaster has been applied.  The effects of this are far-reaching, touching every person who knows of someone who knows of someone who researches (GP)AI.  
On "simpler" ML systems, the effects of these influences only become noticeable via emergence--that is when many such systems are operating in their disparate roles to accomplish a common goal.  That said, the importance of the point I'm making here should not be downplayed.  If AI work is your goal, please consider carefully and proceed with caution regardless of on innocuous you think your work is.

=== Assumptions
This repo and its requirements assume Ubuntu 21.10+ as the host Linux distro.
This project assumes you have an additional drive to use for the various data types hosted by this device.


=== Source Control Management
Mercurial (Python; GPL 2+)


Kallithea (Python, GPL 3)

*Requirements*

- Base server should have podman in its repositories and run on a Raspberry Pi and support v2 cgroups, fully.
- Reliable high volume write capable storage of >= 256GiB, named "REPLICANT2'
- `sudo` group must be passwordless

NOTE: Storage will be carved as:
Single GPT partition (if you skip this, you may be sorry later), carve with lvm2

 * 2 GiB            /vg_data/lv_templates   <-- docker/helm templates
 * 10 GiB           /vg_data/lv_backup      <-- config backup via borg
 * 20% remaining    /vg_data/local          <-- local pipeline space, pod configs
 * 80% remaining    /vg_data/shared         <-- data to be shared (public repos, etc)

NOTE: Run `ansible-galaxy collection install community.general` to meet the requirements to run the install playbook.

=== CI/CD Framework
Buildbot (Python; GPL 2)


=== Build Automation Tool
BitBake (Python; GPL 2)


=== Application Specific

==== _Web Applications Server_
Gunicorn (Python; MIT)
Lighttpd (C; BSD 3-Clause)

==== _RDBMS_
PostgresQL (C, C++, Python, HTML, CMake; PostgreSQL License)

==== _NoSQL Document DB_
ArangoDB (C++, JavaScript; Apache 2.0)

==== _Graph Datastore_
ArangoDB (C++, JavaScript; Apache 2.0)

==== _Key:Value Store_
ArangoDB (C++, JavaScript; Apache 2.0)

==== _Full Text Search Engine_
ArangoDB (C++, JavaScript; Apache 2.0)


=== Code Test Framework
Tox (Python; MIT)


=== Code Quality Suggestion
Tox (Python; MIT)


=== Middleware Automation
Ansible (Python; GPL 2.0) 
NOTE: Considering Saltstack as it may be more complete for this use case.

=== Project Management 
Trac (Python, HTML, JavaScript, CSS; 3-clause BSD)


=== RPi Recommendations

- RPi 3B+ (or newer)
- 16GB microSD for the OS
- USB attached drive of at least 64GiB for Docker persistence which includes the IPFS store which holds configs and the git repo.

If you have some Raspberry Pi 3B/3B+ lying around, use those.  This is sufficient for up to 5 people working on a project unless there is a fair amount of C/C++/Go/Rust to compile.

=== PSA
Please be responsible and do not use this to manage Java.  You should actively discourage the use of Java.  Java eats brains and poisons the water supply^1^.

^1^ _This is an unverified claim.  Of course, if you are using Java you may not be able to verify the claim because it has been eating your brain._


=== NOTES and TODO's
1. Hosting a VCS via an IPFS cluster might present some problems with concurrency due to latency over the Internet; looking for resolutions.  In theory Mercurial + IPFS's Merkle DAG should resolve, but I am REALLY good at finding corner cases where things break horrifically.
2. Arch is a popular distro.  Need to learn Ansible better so I can support Arch as well if it meets the baseline requirements.

