:hide-uri-scheme:

== PortaCode
A template for a lightweight decentralized CD/CI server stack for a very small (< 5 people) group project.


=== What is This?
This code sets up a CD/CI server stack which includes

- Private IPFS instance (see https://github.com/cryptix/git-remote-ipfs.git)
- Docker
- Gogs (w/ SQLite3)
- BuildBot
- and more to come.

The aim is to produce a distributed, lightweight dev server which will go on anything from an RPi3B+ to a powerful VM or Bare Metal.
With this you could use a few RPi3B+ which you share with friends, and host your own code repo cloud with a URL reachable via IPFS for those with whom you have shared the IPFS URI.  If you plan to use this with more than a few people, you'll need both an RPi 4 (or better) with 8GB of RAM, and PostgreSQL.  MariaDB is an option as well, but I've seen several issues with Galera over WAN links; PostgreSQL is slightly better.  Accepting suggestions for a better RDBMS for this use case.


== Why make this?
You reasons to use this are your own.  As for me: I have a strong disdain and distrust for centralized systems, espeically those supported by a profit motive.  The owner of GitHub in particular has a tendency to Embrace, Enhance, and Extenguish.  In this case, they are using your code hosted here (license permitting) to train AI to write code.  This behavior is, in general, a bad idea.


=== Assumptions
This repo and its requirements assume Debian (stable or testing) as the host Linux distro.
This project assumes you have an additional drive formatted with Ext4 and mounted to /data.


=== Requirements
- Ansible 2.x+ (via pip)
- aptitude
- git


=== Installation
1. Have a VM or physical host (RPi?) to install to.
2. Install Debian stable/testing to it.  A preseed ISO could be a good idea.
3. Boot your device.
4. Set up a user to use sudo without a password; prohibit SSH login without key.
5. run `sudo apt install -y aptitude git python3-pip`
6. Install ansible via pip with `python3 -m pip install ansible`
7. Setup the additional drive
  a. Create a GPT partition
  b. Format with Ext4
  c. Mount at /data
8. Clone this repo to your home folder or somewhere.
9. cd into this repo's directory
10. run `ansible-playbook portacode.yml`

On an RPi3B+ this takes about 15 minutes to set up.


=== RPi Recommendations

- RPi 3B+ (or newer)
- 16GB microSD for the OS
- USB attached drive of at least 64GiB for Docker persistence which includes the IPFS store which holds configs and the git repo.

If you have some Raspberry Pi 3B/3B+ lying around, use those.  This is sufficient for up to 5 people working on a project, unless there is a fair amount of C/C++/Go/Rust to compile.

=== PSA
Please be responsible and do not use this to manage Java.  You should actively discourage the use of Java.  Java eats brains and poisons the water supply^1^.

^1^ _This is an unverified claim.  Of course, if your using Java you may not be able to verify the claim because it's been eating your brain._


=== NOTES and TODO's
1. Hosting a VCS via an IPFS cluster might present some problems with concurrency due to latency over the Internet; looking for resolutions.  In theory Git + IPFS's Merkle DAG should resolve, but I am REALLY good at finding corner cases where things break horrificly.
2. Arch is a popular distro.  Need to learn Ansible better so I can support Arch as well.

